In [14]:
import pandas as pd
import numpy as np

In [2]:
CCTV_seoul = pd.read_csv('01. CCTV_in_Seoul.csv', encoding = 'utf-8')
CCTV_seoul.head()

기관명    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  2780       1292    430    584    932
1  강동구   773        379     99    155    377
2  강북구   748        369    120    138    204
3  강서구   884        388    258    184     81
4  관악구  1496        846    260    390    613

In [3]:
CCTV_seoul.rename(columns={CCTV_seoul.columns[0] : '구별'}, inplace=True)
# rename - columns name 변경해줌
CCTV_seoul.head() 

구별    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  2780       1292    430    584    932
1  강동구   773        379     99    155    377
2  강북구   748        369    120    138    204
3  강서구   884        388    258    184     81
4  관악구  1496        846    260    390    613

In [4]:
CCTV_seoul['최근증가율'] = (CCTV_seoul['2016년'] + CCTV_seoul['2015년'] + \
                       CCTV_seoul['2014년']) / CCTV_seoul['2013년도 이전'] * 100
CCTV_seoul.sort_values(by='최근증가율', ascending=False).head()

구별    소계  2013년도 이전  2014년  2015년  2016년       최근증가율
22  종로구  1002        464    314    211    630  248.922414
9   도봉구   485        238    159     42    386  246.638655
12  마포구   574        314    118    169    379  212.101911
8   노원구  1265        542     57    451    516  188.929889
1   강동구   773        379     99    155    377  166.490765

In [5]:
pop_seoul = pd.read_excel('01. population_in_Seoul.xls',encoding = 'utf-8')
pop_seoul.head()

기간  자치구       세대        인구     인구.1     인구.2     인구.3     인구.4  \
0        기간  자치구       세대        합계       합계       합계      한국인      한국인   
1        기간  자치구       세대         계       남자       여자        계       남자   
2  2017.1/4   합계  4202888  10197604  5000005  5197599  9926968  4871560   
3  2017.1/4  종로구    72654    162820    79675    83145   153589    75611   
4  2017.1/4   중구    59481    133240    65790    67450   124312    61656   

      인구.5    인구.6    인구.7    인구.8  세대당인구  65세이상고령자  
0      한국인   등록외국인   등록외국인   등록외국인  세대당인구  65세이상고령자  
1       여자       계      남자      여자  세대당인구  65세이상고령자  
2  5055408  270636  128445  142191   2.36   1321458  
3    77978    9231    4064    5167   2.11     25425  
4    62656    8928    4134    4794   2.09     20764

In [19]:
pop_seoul = pd.read_excel('01. population_in_Seoul.xls',
                          header = 2,
                          usecols = 'B, D, G, J, N',
                          encoding = 'utf-8')
pop_seoul.head()

자치구           계        계.1       계.2   65세이상고령자
0   합계  10197604.0  9926968.0  270636.0  1321458.0
1  종로구    162820.0   153589.0    9231.0    25425.0
2   중구    133240.0   124312.0    8928.0    20764.0
3  용산구    244203.0   229456.0   14747.0    36231.0
4  성동구    311244.0   303380.0    7864.0    39997.0

In [20]:
pop_seoul.rename(columns={pop_seoul.columns[0] : '구별',
                          pop_seoul.columns[1] : '인구수',
                          pop_seoul.columns[2] : '한국인',
                          pop_seoul.columns[3] : '외국인',
                          pop_seoul.columns[4] : '고령자'}, inplace = True )
pop_seoul.head()

구별         인구수        한국인       외국인        고령자
0   합계  10197604.0  9926968.0  270636.0  1321458.0
1  종로구    162820.0   153589.0    9231.0    25425.0
2   중구    133240.0   124312.0    8928.0    20764.0
3  용산구    244203.0   229456.0   14747.0    36231.0
4  성동구    311244.0   303380.0    7864.0    39997.0

In [31]:
pop_seoul['외국인비율'] = pop_seoul['외국인'] / pop_seoul['인구수'] *100
pop_seoul['고령자비율'] = pop_seoul['고령자'] / pop_seoul['인구수'] *100
pop_seoul.head()

구별         인구수        한국인       외국인        고령자     외국인비율      고령자비율
0   합계  10197604.0  9926968.0  270636.0  1321458.0  2.653918  12.958515
1  종로구    162820.0   153589.0    9231.0    25425.0  5.669451  15.615404
2   중구    133240.0   124312.0    8928.0    20764.0  6.700690  15.583909
3  용산구    244203.0   229456.0   14747.0    36231.0  6.038828  14.836427
4  성동구    311244.0   303380.0    7864.0    39997.0  2.526635  12.850689

In [32]:
data_result = pd.merge(CCTV_seoul, pop_seoul, on='구별')
data_result.head()

구별    소계  2013년도 이전  2014년  2015년  2016년       최근증가율       인구수       한국인  \
0  강남구  2780       1292    430    584    932  150.619195  570500.0  565550.0   
1  강동구   773        379     99    155    377  166.490765  453233.0  449019.0   
2  강북구   748        369    120    138    204  125.203252  330192.0  326686.0   
3  강서구   884        388    258    184     81  134.793814  603772.0  597248.0   
4  관악구  1496        846    260    390    613  149.290780  525515.0  507203.0   

       외국인      고령자     외국인비율      고령자비율  
0   4950.0  63167.0  0.867660  11.072217  
1   4214.0  54622.0  0.929765  12.051638  
2   3506.0  54813.0  1.061806  16.600342  
3   6524.0  72548.0  1.080540  12.015794  
4  18312.0  68082.0  3.484582  12.955291

In [33]:
# 의미없는 columns지우기 -- 행방향 삭제(drop), 열삭제(del)
del data_result['2013년도 이전']
del data_result['2014년']
del data_result['2015년']
del data_result['2016년']
data_result.head()

구별    소계       최근증가율       인구수       한국인      외국인      고령자     외국인비율  \
0  강남구  2780  150.619195  570500.0  565550.0   4950.0  63167.0  0.867660   
1  강동구   773  166.490765  453233.0  449019.0   4214.0  54622.0  0.929765   
2  강북구   748  125.203252  330192.0  326686.0   3506.0  54813.0  1.061806   
3  강서구   884  134.793814  603772.0  597248.0   6524.0  72548.0  1.080540   
4  관악구  1496  149.290780  525515.0  507203.0  18312.0  68082.0  3.484582   

       고령자비율  
0  11.072217  
1  12.051638  
2  16.600342  
3  12.015794  
4  12.955291

In [34]:
# set_index ; 그래프 그릴때 row의 index가 구 이름이 되면 유리함
data_result.set_index('구별',inplace=True)
data_result.head()

소계       최근증가율       인구수       한국인      외국인      고령자     외국인비율  \
구별                                                                      
강남구  2780  150.619195  570500.0  565550.0   4950.0  63167.0  0.867660   
강동구   773  166.490765  453233.0  449019.0   4214.0  54622.0  0.929765   
강북구   748  125.203252  330192.0  326686.0   3506.0  54813.0  1.061806   
강서구   884  134.793814  603772.0  597248.0   6524.0  72548.0  1.080540   
관악구  1496  149.290780  525515.0  507203.0  18312.0  68082.0  3.484582   

         고령자비율  
구별              
강남구  11.072217  
강동구  12.051638  
강북구  16.600342  
강서구  12.015794  
관악구  12.955291

### 상관계수의 절대값이 클수록 두 데이터는 관계가 있다
 - 절대 값이 0.1이하면 무시, 0.3이하면 약한 상관관계, 0.7이하면 뚜렷한 상관관계
 - 대각선을 기준으로 대칭인 행렬이고 대각선 때고 다른 값으로 읽는다.

In [36]:
np.corrcoef(data_result['고령자비율'],data_result['소계'])

array([[ 1.        , -0.28078554],
       [-0.28078554,  1.        ]])

In [37]:
np.corrcoef(data_result['외국인비율'],data_result['소계'])

array([[ 1.        , -0.13607433],
       [-0.13607433,  1.        ]])

In [38]:
np.corrcoef(data_result['인구수'],data_result['소계'])

array([[1.        , 0.30634228],
       [0.30634228, 1.        ]])

In [39]:
data_result.sort_values(by='소계', ascending=False).head()

소계       최근증가율       인구수       한국인      외국인      고령자     외국인비율  \
구별                                                                      
강남구  2780  150.619195  570500.0  565550.0   4950.0  63167.0  0.867660   
양천구  2034   34.671731  479978.0  475949.0   4029.0  52975.0  0.839413   
서초구  1930   63.371266  450310.0  445994.0   4316.0  51733.0  0.958451   
은평구  1873   85.237258  494388.0  489943.0   4445.0  72334.0  0.899091   
용산구  1624   53.216374  244203.0  229456.0  14747.0  36231.0  6.038828   

         고령자비율  
구별              
강남구  11.072217  
양천구  11.036964  
서초구  11.488308  
은평구  14.631019  
용산구  14.836427

In [41]:
data_result.sort_values(by='인구수',ascending=False).head()

소계       최근증가율       인구수       한국인      외국인      고령자     외국인비율  \
구별                                                                      
송파구   618  104.347826  667483.0  660584.0   6899.0  72506.0  1.033584   
강서구   884  134.793814  603772.0  597248.0   6524.0  72548.0  1.080540   
강남구  2780  150.619195  570500.0  565550.0   4950.0  63167.0  0.867660   
노원구  1265  188.929889  569384.0  565565.0   3819.0  71941.0  0.670725   
관악구  1496  149.290780  525515.0  507203.0  18312.0  68082.0  3.484582   

         고령자비율  
구별              
송파구  10.862599  
강서구  12.015794  
강남구  11.072217  
노원구  12.634883  
관악구  12.955291